-- MySQL Script generated by MySQL Workbench
-- Fri Dec 18 16:04:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SUPERMERCADO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SUPERMERCADO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SUPERMERCADO` DEFAULT CHARACTER SET utf8 ;
USE `SUPERMERCADO` ;

-- -----------------------------------------------------
-- Table `SUPERMERCADO`.`supermercado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUPERMERCADO`.`supermercado` (
  `nombre` VARCHAR(20) NOT NULL,
  `ubicacion` VARCHAR(60) NOT NULL,
  `hora_cierre` TIME NOT NULL,
  `hora_apertura` TIME NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUPERMERCADO`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUPERMERCADO`.`producto` (
  `id_producto` INT NOT NULL,
  `precio` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `stock_general` INT NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUPERMERCADO`.`cliente_socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUPERMERCADO`.`cliente_socio` (
  `codigo_cliente` INT NOT NULL,
  `CP` INT NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `dirección` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cuenta_bancaria` VARCHAR(45) NOT NULL,
  `bonificación` DECIMAL(3) NOT NULL,
  PRIMARY KEY (`codigo_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUPERMERCADO`.`cliente_NoSocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUPERMERCADO`.`cliente_NoSocio` (
  `codigo_cliente` INT NOT NULL,
  `CP` INT NOT NULL,
  PRIMARY KEY (`codigo_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUPERMERCADO`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUPERMERCADO`.`compra` (
  `fecha` DATE NOT NULL,
  `id_caja` VARCHAR(10) NOT NULL,
  `factura` VARCHAR(45) NOT NULL,
  `hora` TIME NULL,
  `cliente_socio_codigo_cliente` INT NULL,
  `cliente_NoSocio_codigo_cliente` INT NULL,
  `supermercado_nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`factura`),
  INDEX `fk_compra_cliente_socio1_idx` (`cliente_socio_codigo_cliente` ASC) VISIBLE,
  INDEX `fk_compra_cliente_NoSocio1_idx` (`cliente_NoSocio_codigo_cliente` ASC) VISIBLE,
  INDEX `fk_compra_supermercado1_idx` (`supermercado_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_compra_cliente_socio1`
    FOREIGN KEY (`cliente_socio_codigo_cliente`)
    REFERENCES `SUPERMERCADO`.`cliente_socio` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_cliente_NoSocio1`
    FOREIGN KEY (`cliente_NoSocio_codigo_cliente`)
    REFERENCES `SUPERMERCADO`.`cliente_NoSocio` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_supermercado1`
    FOREIGN KEY (`supermercado_nombre`)
    REFERENCES `SUPERMERCADO`.`supermercado` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUPERMERCADO`.`proveedor_nacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUPERMERCADO`.`proveedor_nacional` (
  `nombre` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUPERMERCADO`.`proveedor_extranjero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUPERMERCADO`.`proveedor_extranjero` (
  `nombre` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUPERMERCADO`.`supermercado_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUPERMERCADO`.`supermercado_has_producto` (
  `supermercado_nombre` VARCHAR(20) NOT NULL,
  `producto_id_producto` INT NOT NULL,
  `stock_almacen` INT NOT NULL,
  PRIMARY KEY (`supermercado_nombre`, `producto_id_producto`),
  INDEX `fk_supermercado_has_producto_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  INDEX `fk_supermercado_has_producto_supermercado1_idx` (`supermercado_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_supermercado_has_producto_supermercado1`
    FOREIGN KEY (`supermercado_nombre`)
    REFERENCES `SUPERMERCADO`.`supermercado` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supermercado_has_producto_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `SUPERMERCADO`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUPERMERCADO`.`compra_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUPERMERCADO`.`compra_has_producto` (
  `compra_factura` VARCHAR(45) NOT NULL,
  `producto_id_producto` INT NOT NULL,
  `cantidad_producto` INT NOT NULL,
  PRIMARY KEY (`compra_factura`, `producto_id_producto`),
  INDEX `fk_compra_has_producto_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  INDEX `fk_compra_has_producto_compra1_idx` (`compra_factura` ASC) VISIBLE,
  CONSTRAINT `fk_compra_has_producto_compra1`
    FOREIGN KEY (`compra_factura`)
    REFERENCES `SUPERMERCADO`.`compra` (`factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_has_producto_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `SUPERMERCADO`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUPERMERCADO`.`producto_has_proveedor_nacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUPERMERCADO`.`producto_has_proveedor_nacional` (
  `producto_id_producto` INT NOT NULL,
  `proveedor_nacional_nombre` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`producto_id_producto`, `proveedor_nacional_nombre`),
  INDEX `fk_producto_has_proveedor_nacional_proveedor_nacional1_idx` (`proveedor_nacional_nombre` ASC) VISIBLE,
  INDEX `fk_producto_has_proveedor_nacional_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_producto_has_proveedor_nacional_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `SUPERMERCADO`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_proveedor_nacional_proveedor_nacional1`
    FOREIGN KEY (`proveedor_nacional_nombre`)
    REFERENCES `SUPERMERCADO`.`proveedor_nacional` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUPERMERCADO`.`producto_has_proveedor_extranjero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUPERMERCADO`.`producto_has_proveedor_extranjero` (
  `producto_id_producto` INT NOT NULL,
  `proveedor_extranjero_nombre` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`producto_id_producto`, `proveedor_extranjero_nombre`),
  INDEX `fk_producto_has_proveedor_extranjero_proveedor_extranjero1_idx` (`proveedor_extranjero_nombre` ASC) VISIBLE,
  INDEX `fk_producto_has_proveedor_extranjero_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_producto_has_proveedor_extranjero_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `SUPERMERCADO`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_proveedor_extranjero_proveedor_extranjero1`
    FOREIGN KEY (`proveedor_extranjero_nombre`)
    REFERENCES `SUPERMERCADO`.`proveedor_extranjero` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `SUPERMERCADO`;

DELIMITER $$
USE `SUPERMERCADO`$$
CREATE DEFINER = CURRENT_USER TRIGGER `SUPERMERCADO`.`stock_BEFORE_INSERT` BEFORE INSERT ON `compra_has_producto` FOR EACH ROW
BEGIN
SET @producto = NEW.producto_id_producto;
  SET @cantidad_producto = NEW.cantidad_producto;
  SELECT stock_almacen INTO @stock_almacen FROM supermercado_has_producto WHERE producto_id_producto = @producto;
  SELECT stock_general INTO @stock_general FROM producto WHERE id_producto = @producto;
  IF @stock_almacen > @cantidad_producto THEN
    UPDATE producto SET stock_general = @stock_general - @cantidad_producto WHERE id_producto = @producto;
    UPDATE supermercado_has_producto SET stock_almacen = @stock_almacen - @cantidad_producto WHERE producto_id_producto = @producto;
  ELSE
    SIGNAL SQLSTATE 'ERR0R' SET MESSAGE_TEXT = 'No hay stock suficiente del producto';
  END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
